const android = './app/assets/platforms/platform-android.svg',
    androidForDark = './app/assets/platforms/platform-androidForDark.svg',
    anygame = './app/assets/platforms/platform-anygame.svg',
    anygameForDark = './app/assets/platforms/platform-anygameForDark.svg',
    atari = './app/assets/platforms/platform-atari.svg',
    atariForDark = './app/assets/platforms/platform-atariForDark.svg',
    gamecube = './app/assets/platforms/platform-gamecube.svg',
    gamecubeForDark = './app/assets/platforms/platform-gamecubeForDark.svg',
    macos = './app/assets/platforms/platform-macos.svg',
    macosForDark = './app/assets/platforms/platform-macosForDark.svg',
    ios = './app/assets/platforms/platform-ios.svg',
    iosForDark = './app/assets/platforms/platform-iosForDark.svg',
    linux = './app/assets/platforms/platform-linux.svg',
    linuxForDark = './app/assets/platforms/platform-linuxForDark.svg',
    mobile = './app/assets/platforms/platform-mobile.svg',
    mobileForDark = './app/assets/platforms/platform-mobileForDark.svg',
    nintendo = './app/assets/platforms/platform-nintendo.svg',
    nintendoForDark = './app/assets/platforms/platform-nintendoForDark.svg',
    pc = './app/assets/platforms/platform-pc.svg',
    pcForDark = './app/assets/platforms/platform-pcForDark.svg',
    playstation = './app/assets/platforms/platform-playstation.svg',
    playstationForDark = './app/assets/platforms/platform-playstationForDark.svg',
    sega = './app/assets/platforms/platform-sega.svg',
    segaForDark = './app/assets/platforms/platform-segaForDark.svg',
    n_switch = './app/assets/platforms/platform-switch.svg',
    n_switchForDark = './app/assets/platforms/platform-switchForDark.svg',
    vr = './app/assets/platforms/platform-vr.svg',
    vrForDark = './app/assets/platforms/platform-vrForDark.svg',
    xbox = './app/assets/platforms/platform-xbox.svg',
    xboxForDark = './app/assets/platforms/platform-xboxForDark.svg'

export default {
    android,
    androidForDark,
    anygame,
    anygameForDark,
    atari,
    atariForDark,
    gamecube,
    gamecubeForDark,
    ios,
    iosForDark,
    macos,
    macosForDark,
    linux,
    linuxForDark,
    mobile,
    mobileForDark,
    nintendo,
    nintendoForDark,
    pc,
    pcForDark,
    playstation,
    playstationForDark,
    sega,
    segaForDark,
    n_switch,
    n_switchForDark,
    vr,
    vrForDark,
    xbox,
    xboxForDark
}
